spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
  mail:
    properties:
      mail:
        smtp:
          auth: ${SMTP_AUTH}
          starttls:
            enable: ${SMTP_TLS}

authora:
  jwt:
    secret: ${JWT_SECRET}
  password-policy:
    pepper: ${PW_PEPPER}
  features:
    email-verification-required: true
    audit-log-enabled: true
  cors:
    allowed-origins:
      - https://authora.bermeb.dev

logging:
  level:
    dev.bermeb.authora: WARN
    root: ERROR