spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

authora:
  jwt:
    secret: ${JWT_SECRET}
  features:
    email-verification-required: true
    audit-log-enabled: true

logging:
  level:
    dev.bermeb.authora: WARN
    root: ERROR